# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_client.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(334, 492)
        self.pushButton_call = QtWidgets.QPushButton(Dialog)
        self.pushButton_call.setGeometry(QtCore.QRect(120, 450, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_call.setFont(font)
        self.pushButton_call.setObjectName("pushButton_call")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 50, 271, 385))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_2_modify = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_2_modify.setFont(font)
        self.radioButton_2_modify.setObjectName("radioButton_2_modify")
        self.gridLayout.addWidget(self.radioButton_2_modify, 1, 1, 1, 1)
        self.value_1_x = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.value_1_x.setFont(font)
        self.value_1_x.setText("")
        self.value_1_x.setObjectName("value_1_x")
        self.gridLayout.addWidget(self.value_1_x, 4, 2, 1, 1)
        self.value_2_y = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.value_2_y.setFont(font)
        self.value_2_y.setText("")
        self.value_2_y.setObjectName("value_2_y")
        self.gridLayout.addWidget(self.value_2_y, 5, 2, 1, 1)
        self.label_4_id = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4_id.setFont(font)
        self.label_4_id.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_4_id.setObjectName("label_4_id")
        self.gridLayout.addWidget(self.label_4_id, 7, 1, 1, 1)
        self.radioButton_3_insert = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_3_insert.setFont(font)
        self.radioButton_3_insert.setObjectName("radioButton_3_insert")
        self.gridLayout.addWidget(self.radioButton_3_insert, 2, 1, 1, 1)
        self.value_3_yaw = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.value_3_yaw.setFont(font)
        self.value_3_yaw.setText("")
        self.value_3_yaw.setObjectName("value_3_yaw")
        self.gridLayout.addWidget(self.value_3_yaw, 6, 2, 1, 1)
        self.title_1_mode = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(13)
        self.title_1_mode.setFont(font)
        self.title_1_mode.setObjectName("title_1_mode")
        self.gridLayout.addWidget(self.title_1_mode, 0, 0, 1, 1)
        self.edit_id = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.edit_id.setFont(font)
        self.edit_id.setObjectName("edit_id")
        self.gridLayout.addWidget(self.edit_id, 7, 2, 1, 1)
        self.title_waypoint = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(13)
        self.title_waypoint.setFont(font)
        self.title_waypoint.setObjectName("title_waypoint")
        self.gridLayout.addWidget(self.title_waypoint, 4, 0, 1, 1)
        self.radioButton_1_add = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_1_add.setFont(font)
        self.radioButton_1_add.setObjectName("radioButton_1_add")
        self.gridLayout.addWidget(self.radioButton_1_add, 0, 1, 1, 1)
        self.label_2_y = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2_y.setFont(font)
        self.label_2_y.setObjectName("label_2_y")
        self.gridLayout.addWidget(self.label_2_y, 5, 1, 1, 1)
        self.label_1_x = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_1_x.setFont(font)
        self.label_1_x.setObjectName("label_1_x")
        self.gridLayout.addWidget(self.label_1_x, 4, 1, 1, 1)
        self.radioButton_4_delete = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_4_delete.setFont(font)
        self.radioButton_4_delete.setObjectName("radioButton_4_delete")
        self.gridLayout.addWidget(self.radioButton_4_delete, 3, 1, 1, 1)
        self.label_3_yaw = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3_yaw.setFont(font)
        self.label_3_yaw.setObjectName("label_3_yaw")
        self.gridLayout.addWidget(self.label_3_yaw, 6, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5_result = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5_result.setFont(font)
        self.label_5_result.setObjectName("label_5_result")
        self.verticalLayout.addWidget(self.label_5_result)
        self.text_result = QtWidgets.QTextBrowser(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.text_result.setFont(font)
        self.text_result.setObjectName("text_result")
        self.verticalLayout.addWidget(self.text_result)
        self.gridLayout.addLayout(self.verticalLayout, 8, 0, 1, 3)
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(30, 10, 51, 30))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.pushButton_undo = QtWidgets.QPushButton(self.splitter)
        self.pushButton_undo.setObjectName("pushButton_undo")
        self.pushButton_redo = QtWidgets.QPushButton(self.splitter)
        self.pushButton_redo.setObjectName("pushButton_redo")

        self.retranslateUi(Dialog)
        self.radioButton_1_add.clicked.connect(Dialog.clicked_add)
        self.radioButton_2_modify.clicked.connect(Dialog.clicked_modify)
        self.radioButton_3_insert.clicked.connect(Dialog.clicked_insert)
        self.radioButton_4_delete.clicked.connect(Dialog.clicked_delete)
        self.pushButton_call.clicked.connect(Dialog.call)
        self.pushButton_undo.clicked.connect(Dialog.undo)
        self.pushButton_redo.clicked.connect(Dialog.redo)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.radioButton_1_add, self.radioButton_2_modify)
        Dialog.setTabOrder(self.radioButton_2_modify, self.radioButton_3_insert)
        Dialog.setTabOrder(self.radioButton_3_insert, self.radioButton_4_delete)
        Dialog.setTabOrder(self.radioButton_4_delete, self.edit_id)
        Dialog.setTabOrder(self.edit_id, self.text_result)
        Dialog.setTabOrder(self.text_result, self.pushButton_call)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_call.setText(_translate("Dialog", "call"))
        self.radioButton_2_modify.setText(_translate("Dialog", "modify"))
        self.label_4_id.setText(_translate("Dialog", "id:"))
        self.radioButton_3_insert.setText(_translate("Dialog", "insert"))
        self.title_1_mode.setText(_translate("Dialog", "Edit Mode"))
        self.title_waypoint.setText(_translate("Dialog", "Waypoint"))
        self.radioButton_1_add.setText(_translate("Dialog", "add"))
        self.label_2_y.setText(_translate("Dialog", "y:"))
        self.label_1_x.setText(_translate("Dialog", "x:"))
        self.radioButton_4_delete.setText(_translate("Dialog", "delete"))
        self.label_3_yaw.setText(_translate("Dialog", "yaw:"))
        self.label_5_result.setText(_translate("Dialog", "Result"))
        self.pushButton_undo.setText(_translate("Dialog", "←"))
        self.pushButton_redo.setText(_translate("Dialog", "→"))
